# Generated by Django 5.2 on 2025-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypeTable', '0003_currencyconverter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconverter',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
