# Generated by Django 5.2 on 2025-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypeTable', '0004_alter_currencyconverter_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconverter',
            name='base_currencybase_currency',
            field=models.CharField(max_length=3),
        ),
    ]
