# Generated by Django 5.2 on 2025-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TypeTable', '0005_alter_currencyconverter_base_currencybase_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyconverter',
            old_name='base_currencybase_currency',
            new_name='base_currency',
        ),
    ]
