# Generated by Django 5.2 on 2025-05-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypeTable', '0006_rename_base_currencybase_currency_currencyconverter_base_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('property_type', models.CharField(blank=True, choices=[('Residential', 'Residential Types'), ('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('chalet', 'Chalet'), ('Commercial', 'Commercial Types'), ('office', 'Office'), ('retail', 'Retail Space'), ('shop', 'Shop'), ('warehouse', 'Warehouse')], max_length=20, null=True, verbose_name='Property Type')),
                ('status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented')], max_length=20, verbose_name='Status')),
                ('property_status', models.CharField(choices=[('resale', 'Resale'), ('primary', 'Primary')], default='resale', max_length=20, verbose_name='Property Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], default='EGP', max_length=3, verbose_name='Currency')),
                ('area', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10, verbose_name='Area')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Bathrooms')),
                ('garage', models.PositiveIntegerField(default=0, verbose_name='Garage')),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Initial payment amount', max_digits=12, null=True, verbose_name='Down Payment')),
                ('down_payment_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Down payment as a percentage of total price', max_digits=5, null=True, verbose_name='Down Payment Percentage')),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid monthly in case of installments.', max_digits=12, null=True, verbose_name='Monthly Installment')),
                ('installment_duration_years', models.PositiveIntegerField(blank=True, help_text='Total number of years over which the installments are spread.', null=True, verbose_name='Installment Duration (Years)')),
                ('payment_plan', models.CharField(blank=True, choices=[('cash', 'Cash'), ('installment', 'Installment')], help_text='Comma-separated payment plan types (e.g., cash, installments)', max_length=255, verbose_name='Payment Plan')),
                ('payment_plan_ar', models.CharField(blank=True, max_length=255, verbose_name='Payment Plan (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('new_property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TypeTable.propertytype', verbose_name='Property Type')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'indexes': [models.Index(fields=['title'], name='TypeTable_p_title_03ac6f_idx'), models.Index(fields=['property_type'], name='TypeTable_p_propert_bd4b13_idx'), models.Index(fields=['status'], name='TypeTable_p_status_12a10e_idx'), models.Index(fields=['price'], name='TypeTable_p_price_ffc52c_idx'), models.Index(fields=['bedrooms'], name='TypeTable_p_bedroom_4a8559_idx'), models.Index(fields=['bathrooms'], name='TypeTable_p_bathroo_70eaf0_idx'), models.Index(fields=['area'], name='TypeTable_p_area_6c4c68_idx')],
            },
        ),
    ]
