# Generated by Django 5.2 on 2025-05-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TypeTable', '0007_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='installment_duration_years',
        ),
        migrations.RemoveField(
            model_name='property',
            name='monthly_installment',
        ),
        migrations.RemoveField(
            model_name='property',
            name='payment_plan_ar',
        ),
    ]
