# Generated by Django 5.2 on 2025-05-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TypeTable', '0008_remove_property_installment_duration_years_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='TypeTable_p_propert_bd4b13_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
    ]
